CREATE TABLE Sprzet(
id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
data_zakupu DATE NOT NULL,
data_uruchom DATE NOT NULL,
wartosc BIGINT UNSIGNED NOT NULL,
opis TEXT NOT NULL,
projekt INTEGER,
laboratorium INTEGER,
CHECK (data_uruchom>=data_zakupu),
CHECK (wartosc>=0),
FOREIGN KEY (projekt) REFERENCES Projekt(id) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY (laboratorium) REFERENCES Laboratorium(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE Projekt(
id INTEGER PRIMARY KEY AUTOINCREMENT,
nazwa VARCHAR(64) NOT NULL UNIQUE,
data_rozp DATE NOT NULL,
data_zakoncz DATE NOT NULL,
opis TEXT NOT NULL,
logo VARCHAR(128) NOT NULL UNIQUE,
CHECK (data_zakoncz>=data_rozp)
);

CREATE TABLE Osoba(
id INTEGER PRIMARY KEY AUTOINCREMENT,
imie VARCHAR(16) NOT NULL,
nazwisko VARCHAR(32) NOT NULL,
email VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE Kontakt(
sprzet INTEGER NOT NULL,
osoba INTEGER NOT NULL,
FOREIGN KEY (sprzet) REFERENCES Sprzet(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (osoba) REFERENCES Osoba(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Zdjecie(
id INTEGER PRIMARY KEY AUTOINCREMENT,
sprzet INTEGER NOT NULL,
link VARCHAR(128) NOT NULL,
FOREIGN KEY (sprzet) REFERENCES Sprzet(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Tag(
id INTEGER PRIMARY KEY AUTOINCREMENT,
nazwa VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE Tagi_sprzetu(
sprzet INTEGER NOT NULL,
tag INTEGER NOT NULL,
FOREIGN KEY (sprzet) REFERENCES Sprzet(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (tag) REFERENCES Tag(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Laboratorium(
id INTEGER PRIMARY KEY AUTOINCREMENT,
nazwa VARCHAR(64) NOT NULL,
zespol INTEGER NOT NULL,
FOREIGN KEY (zespol) REFERENCES Zespol(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE Zespol(
id INTEGER PRIMARY KEY AUTOINCREMENT,
nazwa VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE Laborat_w_zaklad(
zaklad INTEGER NOT NULL,
laboratorium INTEGER NOT NULL,
FOREIGN KEY (zaklad) REFERENCES Zaklad(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (laboratorium) REFERENCES Laboratorium(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Zaklad(
id INTEGER PRIMARY KEY AUTOINCREMENT,
nazwa VARCHAR(64) NOT NULL UNIQUE
);
