.read "DB setup sqlite.sql"
.read "Uzytkownicy.sql"
.read "Osoba.sql"
.read "Tag.sql"
.read "Zaklad.sql"
.read "Zespol.sql"
.read "Projekt.sql"
.read "Sprzet.sql"
.read "Kontakt.sql"
.read "Tag.sql"
.read "Tagi_sprzetu.sql"
.read "Laborat_w_zaklad.sql"
.read "Laboratorium.sql"
